### ISSUE TITLE
The GFLOPS for MobileNet v1 and Mobilenet v2 in your paper

### ISSUE THREAD

**Issue by kumardesappan** [CeLuigi/models-comparison.pytorch#1]
May I know the GFLOPS used for MobileNet v1 and Mobilenet v2 in your paper. The numbers look close to 5 GFLOPS but actually, it shall be around 0.56 GFLOPS for 224x224 image. Am I missing something here.?

**Comment by CeLuigi** [comment]
You are right. There is an error in the plots for both MobileNets and ShuffleNet; in fact, the corresponding values obtained running the script in the repo are: MobileNet-v1 --> 0.57; MobileNet-v2 --> 0.31; ShuffleNet --> 0.14. Thanks
